[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]

[tools]
go = "latest"
ruby = "3.4.4"
deno = "latest"
elixir = "latest"
erlang = "latest"
node = "latest"
rust = "latest"
usage = "latest"
