[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]

[tools]
go = "latest"
ruby = "4.0.1"
deno = "latest"
elixir = "1.19.5-otp-28"
erlang = "28.3.1"
node = "latest"
rust = "latest"
usage = "latest"
ast-grep = "latest"
uv = "latest"
dotnet = "8"
curlie = "latest"
